### ISSUE TITLE
Arm Home, Away, and Disarm no longer function

### ISSUE THREAD

**Issue by m-milani** [adt-pulse-mqtt/adt-pulse-mqtt#52]
The Arm Home, Away, and Disarm functions no longer work on the Alarm Control Panel, however the Sensor Status still works.   

Receiving the following dump in the logs:  "You do not have access to the requested feature"
and at the end of the dump - 
**5/23/2022, 4:54:37 PM Pulse setAlarmState Success. Forced?:undefined**

     <td class="p_whiteBoxTopRight"></td>

    </tr>

    <tr>

        <td class="p_whiteBoxMiddleLeft"></td>

        <td class="p_whiteBoxMiddleCenter" align="center">

                    <div class="p_headerShim2">
                        <div class="p_signinLogoStyle">
                            
                            <a href="http://www.adt.com" target="_blank">
                                <div class="p_customLogo"></div>
                            </a>
                        </div>
                    </div>
                    <br/>
<br/>
    **<div id="errorDivMessage">
        <br/>
<div style="text-align:center">You do not have access to the requested feature.</div>
        <br/><br/><br/>**
        <div id="closebtn" style="display:none;"><input type="button" id="close" name="close" value="Close" alt="Close" class="p_btn p_btnXnormal" onclick="javascript:window.close()" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizeclose {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizeclose" class="p_btn p_btnXnormal" >Close</div></div>
        <div id="fullwindow"><input type="button" id="gotoportal" name="gotoportal" value="Return to Portal" alt="Return to Portal" class="p_btn p_btnXnormal" onclick="javascript:goToUrl('/myhome/23.0.0-99/summary/summary.jsp')" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizegotoportal {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizegotoportal" class="p_btn p_btnXnormal" >Return to Portal</div>&nbsp;&nbsp;
                         <input type="button" id="gotosignin" name="gotosignin" value="Go to Sign In" alt="Go to Sign In" class="p_btn p_btnXnormal" onclick="javascript:goToUrl('/myhome/23.0.0-99/access/signin.jsp')" onmouseover="javascript:btnHover(this,'X')" onmouseout="javascript:btnNormal(this,'X')" onmousedown="javascript:btnDown(this,'X')" onmouseup="javascript:btnNormal(this,'X')"  data-fitLabel="shrink"/><style type="text/css">#testSizegotosignin {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizegotosignin" class="p_btn p_btnXnormal" >Go to Sign In</div>
        </div>
        <br><br>
    </div>
    <script type="text/javascript">
        var errorWindow = getPortalScreenDimensions();
        if  (errorWindow.w < 700 || errorWindow.h < 500)
        {
            window.resizeTo( 700, 500 );
        }
        window.setTimeout(()=> {
        	const actionBtn = document.getElementById('gotosignin') || document.getElementById('gotoportal');
	        actionBtn?.focus();
        }, 0);
    </script>
                    

        </td>

        <td class="p_whiteBoxMiddleRight"></td>

    </tr>

    <tr>

        <td class="p_whiteBoxBotLeft"></td>

        <td class="p_whiteBoxBotCenter"></td>

        <td class="p_whiteBoxBotRight"></td>

    </tr>

</table>

                    
                    <div style="width:620px;height:1px;"></div>
                    
                    

         </td>

         <td class='p_raisedBoxMiddleRight'></td>

     </tr>

     <tr>

         <td class='p_raisedBoxFooterLeft'></td>

         <td class='p_raisedBoxFooterCenter' width="100%"></td>

         <td class='p_raisedBoxFooterRight'></td>

     </tr>                   

     <tr>

         <td class='p_raisedBoxBottomLeft'></td>

         <td class='p_raisedBoxBottomCenter'></td>

         <td class='p_raisedBoxBottomRight'></td>

     </tr>

</table>

                    </td>
                </tr>
                <tr height=5><td colspan=2></td></tr>
            </table>
            <span class="p_smallCommentText"><a class="p_footerLink" href="http://www.adt.com" target="_blank">ADT Security Services</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/privacy-policy" target="_blank">Privacy Policy</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/about-adt/legal/adt-pulse-terms-of-use" target="_blank">ADT Pulse Terms of Use</a>
                <span class="p_footerDivider"> | </span><a class="p_footerLink" href="https://www.adt.com/help" target="_blank">Customer Support</a>
                </span>
            <br /><br />
        </div>
        
        </body>
    </html>
::
**5/23/2022, 4:54:37 PM Pulse setAlarmState Success. Forced?:undefined**

**Comment by ay200** [comment]
Same. Looks like it started 3 days ago. Love the project.

**Comment by d0nni3q84** [comment]
Same. Root cause appears to be a new field (`sat`) that is required in the query string when calling `setArmState` via armDisarm.jsp URI. That field seems to be dynamically generated; taking a deeper look and will report back my findings.

**Comment by d0nni3q84** [comment]
Created PR #53 to address this issue where `sat` is **null** as a result of the [RegEx in adt-pulse.js](https://github.com/adt-pulse-mqtt/adt-pulse-mqtt/blob/master/adt-pulse-mqtt/adt-pulse.js#L409) no longer matching the page content. Confirmed by using a sample Node.js routine against the html content fetched after login.

```
$ cat sat-parser.js 
const fs = require('fs');

try {
        const body = fs.readFileSync('index.html', 'utf8');
        //console.log('Looking for SAT using current RegEx /sat=(.+?)&href/ at index 1.');
        console.log('Looking for SAT using current RegEx /sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/ at index 1.');
        //sat = body.match(/sat=(.+?)&href/)[1];
        sat = body.match(/sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/)[1];
        console.log('SAT is:');
        console.log(sat);
} catch (err) {
        console.error(err);
}
```

```
$ node sat-parser.js 
Looking for SAT using current RegEx /sat=(.+?)&href/ at index 1.
TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/home/cloudshell-user/sat-parser.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

```
$ node sat-parser.js 
Looking for SAT using new RegEx /sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/ at index 1.
SAT is:
2bcf17eb-b33e-4998-bb4d-6b285a03cf51
```

**Comment by digitalcraig** [comment]
adtpulsemqtt/adt-pulse-mqtt-armhf:latest and adtpulsemqtt/adt-pulse-mqtt-amd64:latest have been pushed for anyone running the Docker version who can test.

**Comment by ghanjiboy** [comment]
Hi @digitalcraig , I was able to test the docker container built from master and what was broken is now working - essentially I can now arm/disarm several times.

Thanks!

**Comment by RodneyCapron** [comment]
Thank you very much @d0nni3q84 and @digitalcraig for correcting the issue. You rock!! 👍
