### ISSUE TITLE
Add-On crashes when armed "away" or "home"

### ISSUE THREAD

**Issue by m-milani** [adt-pulse-mqtt/adt-pulse-mqtt#55]
Thanks for the quick fix.   However, I was able to arm "home" using the alarm control panel and was not able to disarm.   The add-on had stopped.   Same happens if I arm "away".

Log snippet follows:

/usr/src/app/adt-pulse.js:241
						if (newsat = body.match(/sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/)[1]) { 
						                                                                                             ^
TypeError: Cannot read property '1' of null
    at Request._callback (/usr/src/app/adt-pulse.js:241:100)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@3.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-25T18_51_14_529Z-debug.log

**Comment by digitalcraig** [comment]
v3.1.1 has been released

-  Handle case where a sat value isn't provided
-  Additional checking for null values
-  Revert to previous behavior if sat value isn't available

**Comment by m-milani** [comment]
It unfortunately still crashes after an arming/disarming event.

**Comment by digitalcraig** [comment]
I don't have an ADT system anymore so I will need more information in order to troubleshoot further. Please ensure you have upgraded to 3.1.1 and post the latest logs.

**Comment by kyleanderson90** [comment]
I'm experiencing the same error

**Comment by digitalcraig** [comment]
No additional information to go on, so closing this.
