### ISSUE TITLE
Crashing - Cannot read property '1' of null

### ISSUE THREAD

**Issue by shorki78** [adt-pulse-mqtt/adt-pulse-mqtt#65]
Started having this issue recently, after a HA update. Any idea what could be causing this?

12/19/2023, 9:23:28 AM Pulse: Authentication Success
12/19/2023, 9:23:28 AM Pulse: updateAll
12/19/2023, 9:23:28 AM Pulse.getAlarmStatus: Getting Alarm Statuses
12/19/2023, 9:23:29 AM Pulse.Sync: Syncing 2-0-0
12/19/2023, 9:23:29 AM Pulse: updateAll
12/19/2023, 9:23:29 AM Pulse.getAlarmStatus: Getting Alarm Statuses
12/19/2023, 9:23:29 AM Pulse.Sync: Syncing 470144-446039-1
12/19/2023, 9:23:29 AM Pulse: updateAll
12/19/2023, 9:23:29 AM Pulse.getAlarmStatus: Getting Alarm Statuses
12/19/2023, 9:23:29 AM Pulse.getDeviceStatus: Getting Device Statuses
12/19/2023, 9:23:29 AM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
12/19/2023, 9:23:29 AM Pulse.getDeviceStatus: Getting Device Statuses
12/19/2023, 9:23:29 AM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
12/19/2023, 9:23:29 AM Pulse.getDeviceStatus: Getting Device Statuses
12/19/2023, 9:23:29 AM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
12/19/2023, 9:23:30 AM Pulse.getDeviceStatus No other devices found
12/19/2023, 9:23:30 AM Pulse.getDeviceStatus No other devices found
12/19/2023, 9:23:30 AM ADT Pulse: Get zone status (via orb) success.
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Back Room Glass Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Back Room Glass/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Family Living Perimeter Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Family Living Perimeter/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Family Motion Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Family Motion Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Front Garage Door Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Front Garage Door/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Guest Glass Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Guest Glass Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Hall Bedroom Smoke Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Hall Bedroom Smoke/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Hall Motion Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Hall Motion Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Kid's Bathroom Glass Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Kid's Bathroom Glass/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Kitchen Heat Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Kitchen Heat/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Kitchen Office Window Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Kitchen Office Window/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Laundry Bedroom Bathroom Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Laundry Bedroom Bathroom/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Laundry Glass Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Laundry Glass Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Living Glass Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Living Glass Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Master Bathroom Glass Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Master Bathroom Glass/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Master Bedroom Window Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Master Bedroom Window/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Master Glass Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Master Glass Detector/state
12/19/2023, 9:23:30 AM Sensor: sensor-0 Name: Office Glass Detector Tags: sensor State devStatUnknown
12/19/2023, 9:23:30 AM Pushing device state: devStatUnknown to topic adt/zone/Office Glass Detector/state
/usr/src/app/adt-pulse.js:241
						var newsat = body.match(/sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/)[1]; 
						                                                                                             ^

TypeError: Cannot read property '1' of null
    at Request._callback (/usr/src/app/adt-pulse.js:241:100)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@3.1.11 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@3.1.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shorki78** [comment]
This can be deleted. Something was wrong with the pulse connectivity and the plugin didn't handle it gracefully. Once that was fixed it's working again.

**Comment by shorki78** [comment]
This can be deleted. Something was wrong with the pulse connectivity and the plugin didn't handle it gracefully. Once that was fixed it's working again.
